### ISSUE TITLE
Implement initial riffusion-container

### ISSUE THREAD

**Issue by entelecheia** [entelecheia/riffusion-container#1]
## Summary

Implement a Docker container to run the Riffusion app.

## Tasks

- [ ] Create Dockerfile
  - Use Node.js base image
  - Install Riffusion app dependencies
- [ ] Copy Riffusion app code into image 
- [ ] Create entrypoint script
  - Build and start Next.js server on container startup
- [ ] Expose port 3000
  - For Next.js dev server
- [ ] Create config volume
  - For `.env` with backend URL  
- [ ] Write README
  - Usage
  - Configs
  - Ports
  
## Requirements

- Dockerfile builds Riffusion app image
- Entrypoint launches Next.js dev server on start
- Port 3000 exposed for web app
- Config volume for `.env` file  
- README explains usage and configs

## Resources

- Riffusion app repo: https://github.com/riffusion/riffusion-app
